version: "3"

services:

  postgresql:
    image: postgres:11
    container_name: postgresql1
    ports:
      - "5431:5432"
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - TZ=Asia/Tokyo
      - SUPERUSER_ROLE_NAME=superuser_role
      - SUPERUSER_ROLE_PASSWORD=superuser_pw
      - PROD_DB_NAME=prod_db
      - PROD_SCHEMA_NAME=prod_schema
      - PROD_SCHEMA_ROLE_NAME=prod_schema_role
      - PROD_SCHEMA_ROLE_PASSWORD=prod_schema_role_pw
      - PROD_SCHEMA_READ_ONLY_ROLE_NAME=prod_schema_read_only_role
      - PROD_SCHEMA_READ_ONLY_ROLE_PASSWORD=prod_schema_read_only_role_pw
      - PROD_SCHEMA2_NAME=prod_schema2
      - PROD_SCHEMA2_ROLE_NAME=prod_schema2_role
      - PROD_SCHEMA2_ROLE_PASSWORD=prod_schema2_role_pw
      - STAGING_DB_NAME=staging_db
      - STAGING_SCHEMA_NAME=staging_schema
      - STAGING_SCHEMA_ROLE_NAME=staging_schema_role
      - STAGING_SCHEMA_ROLE_PASSWORD=staging_schema_role_pw
      - DEVELOP_SCHEMA_NAME=develop_schema
      - DEVELOP_SCHEMA_ROLE_NAME=develop_schema_role
      - DEVELOP_SCHEMA_ROLE_PASSWORD=develop_schema_role_pw
#      - POSTGRES_DB=prod_db
#      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C
    volumes:
      - ./volumes/postgresql/datadir:/var/lib/postgresql/data
      - ./volumes/postgresql/initdb.d:/docker-entrypoint-initdb.d
      - ./volumes/postgresql/initdata:/initdata
