version: '3'

services:
  db:
    image: container-registry.oracle.com/database/enterprise:19.3.0.0
    container_name: oracle19c
    privileged: true
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - ./volumes/opt/oracle/oradata/:/opt/oracle/oradata
      - ./volumes/opt/oracle/scripts/startup:/opt/oracle/scripts/startup # コンテナ起動時に実行
    environment:
      - ORACLE_EDITION=standard
      - ORACLE_PWD=passw0rd
      - ORACLE_PDB=ORCLPDB1
