version: '3'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - SUPERUSER_NAME=superuser
      - SUPERUSER_PASSWORD=superuser_pw
      - PROD_DATABASE_NAME=prod_database
      - PROD_USER_NAME=prod_user
      - PROD_USER_PASSWORD=prod_user_pw
      - DEVELOP_DATABASE_NAME=develop_database
      - DEVELOP_USER_NAME=develop_user
      - DEVELOP_USER_PASSWORD=develop_user_pw
    volumes:
      - ./volumes/mysql/datadir:/var/lib/mysql
      - ./volumes/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./volumes/mysql/initdata:/initdata
      - ./volumes/mysql/etc/mysql/conf.d:/etc/mysql/conf.d
